# This file defines the named poses used by the structural tests.
# Each pose must include every joint from `arm.yaml` with tick values within that 
# joint's `position_limits`.

# More poses will be added here as we calibrate the arm. 

poses:
  home: # r_sh_flex / r_farm_rot TBD.
    r_sh_flex: 2048
    r_sh_abd: 3200
    r_sh_rot: 3000
    r_elb_flex: 5500
    r_farm_rot: 2048
    r_wrist_flex: 3700
    r_fin_thumb: 2500
    r_fin_index: 3200
    r_fin_middle: 1900
    r_fin_ring: 1500
    r_fin_pinky: 3000
  
